apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-pingshian
spec:
  rules:
  - host: pingshian.simple-web.tw
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  ingressClassName: nginx
