apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deploy
  namespace: ping-web-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-application
  template:
    metadata:
      labels:
        app: django-application
    spec:
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-pvc
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
      containers:
        - image: pingshian0131/ping-web-kubernetes:latest
          imagePullPolicy: Always
          name: django-app-container
          envFrom:
            - secretRef:
                name: app-secret
          ports:
            - containerPort: 8001
          volumeMounts:
            - mountPath: "/var/www/personal/static/"
              name: static-volume
            - mountPath: "/var/www/personal/media/"
              name: media-volume
