apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
  namespace: ping-web-ns
  labels:
    type: local
    app: django-static
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/www/personal/static/"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  labels:
    type: local
    app: django-media
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/www/personal/media/"